<?php

return [
    [
        'name' => 'wechat_app_app_id',
        'title' => 'APPID',
        'type' => 'string',
        'group' => 'wechat_app',
        'visible' => '',
        'content' => [],
        'value' => 'wxdxxxxxxxx',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'wechat_app_app_secret',
        'title' => 'AppSecret',
        'type' => 'string',
        'group' => 'wechat_app',
        'content' => [],
        'value' => 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
    [
        'name' => 'ali_app_secret',
        'title' => 'AppSecret',
        'type' => 'string',
        'group' => 'ali',
        'content' => [],
        'value' => 'xxxxxxxxxxxxxxxxxxxxxxxxx',
        'rule' => 'required',
        'msg' => '',
        'tip' => '',
        'ok' => '',
        'extend' => '',
    ],
];
